---
title: "emtpb manuscript figures"
author: "Alexander Ohnmacht"
date: "24/10/2023"
output:
  pdf_document: 
    toc: true
    fig_caption: true
    number_sections: true
    fig_width: 12
    fig_height: 12
  html_document:
    toc: true
    fig_caption: true
    number_sections: true
    fig_width: 12
    fig_height: 12
editor_options: 
  chunk_output_type: console
---

```{r set, include=FALSE}
knitr::opts_chunk$set(xtable.comment = FALSE, 
                      echo=T,
                      eval=T, 
                      message = F,
                      warning=F, 
                      error = F,
                      cache = FALSE,
                      tidy = F, 
                      size="footnotesize",
                      fig.pos='H',
                      dev = "pdf",
                      results='markup',
                      fig.lp='fig:',
                      fig.align = 'center',
                      fig.path='figures/v2-', 
                      cache.path = 'cache/v2-',
                      tidy.opts=list(width.cutoff=80), 
                      dev = 'pdf' 
)
knitr::opts_chunk$set(echo = TRUE)
library(yaml)
config <- yaml.load_file("scripts/config.yaml")
path <- config$r_local_path
```

```{r setup, include=FALSE}
library(ggplot2)
library(ggrepel)
library(dplyr)
library(readr)
library(RColorBrewer)
library(plotly)
library(GGally)
library(ggbeeswarm)
library(ggpubr)
library(tidyr)
library(rstatix)
library(tibble)
library(data.table)
library(limma)
library(enrichR)
library(readxl)
library(ComplexHeatmap)
library(circlize)
library(shades)
library(viridis)
library(gridExtra)
library(writexl)

orderedcelllines <- c("SK-MEL-5","IGR-37","RPMI-7951","A375") # put here what cells to highlight (A-375,SK-MEL-1)
validation_aucs <- "metadata/goeksu/exp2/AUCs.xlsx"
validation_ic50s <- "metadata/goeksu/exp2/IC50s.xlsx"

EMTscores <- suppressMessages(read_csv(paste0(path,"metadata/EMTscores","",".csv"))) # BENCHMARKING ORDER FOR GDSC CANCER TYPES
cancertypes <- unique(c('PANCAN', unlist(EMTscores['TCGA Desc'])))
  
df <- readRDS(paste0(path,"metadata/summaries/PERFORMANCES_v3.rds")) # path_calcs
df$pvalue <- unlist(lapply(df$pvalue, function(x){x}))
df$effectsize_mean <- unlist(lapply(df$effectsize_mean, function(x){x}))
df$lower <- unlist(lapply(df$lower, function(x){x}))
df$upper <- unlist(lapply(df$upper, function(x){x}))
df <- df %>%
  dplyr::select(-c(effectsize, inference))


drug_meta <- read_csv(paste0(path,"data/screened_compounds_rel_8.4.csv")) %>% 
  mutate(drugname = DRUG_NAME, target = TARGET, pathway = TARGET_PATHWAY) %>%
  select(c(drugname, pathway)) %>% # target
  distinct()
drug_meta <- drug_meta[!drug_meta$drugname %>% duplicated,]
df <- left_join(df, drug_meta, by = "drugname")


# EMT scores
EMTscores_mak <- suppressMessages(read_csv(paste0(path,"metadata/EMTscores","",".csv"))) #%>% mutate(EMT_score = -EMT_score) #%>% mutate(method = "mak")
EMTscores_gsva <- suppressMessages(read_csv(paste0(path,"metadata/EMTscores","_gsva",".csv"))) #%>% mutate(method = "gsva")
EMTscores_tan <- suppressMessages(read_csv(paste0(path,"metadata/EMTscores","_tan_088",".csv"))) #%>% mutate(method = "tan")
EMTscores_tagliazucchi <- suppressMessages(read_csv(paste0(path,"metadata/EMTscores","_secrier_065",".csv"))) #%>% mutate(method = "secrier")
emt <- full_join(full_join(full_join(EMTscores_mak, EMTscores_gsva, by = "COSMIC ID"), EMTscores_tan, by = "COSMIC ID"), EMTscores_tagliazucchi, by = "COSMIC ID")
emtp <- select_if(emt, is.numeric)
emtp$TCGA <- factor(emt$`TCGA Desc.x`)
emtp_save <- emtp
colnames(emtp_save) <- c("COSMIC ID","mak","gsva","tan","tagliazucchi","TCGA Desc")
emtp <- emtp[emtp$TCGA %in% c("BRCA","SKCM","LUAD","SCLC","GBM","COREAD"),]
emtp$TCGA <- factor(emtp$TCGA)
colnames(emtp) <- c("COSMIC ID","mak","gsva","tan","tagliazucchi","TCGA Desc")


# responses
resp_ic50 = suppressMessages(read_csv(paste0(path,"metadata/matrix_resp","",".csv"))) # %>% dplyr::select(-c("COSMIC ID","TCGA Desc")))
resp_auc = suppressMessages(read_csv(paste0(path,"metadata/matrix_resp","_auc",".csv"))) # %>% dplyr::select(-c("COSMIC ID","TCGA Desc")))

# get experiments
experiment <- read_csv(paste0(path,"metadata/paper/benchmark_paper_exp3+6_03_pool.csv"), na = character())
#experiment_full <- read_csv(paste0(path,"metadata/paper/benchmark_paper_exp3.csv"), na = character())
#experiment_second <- read_csv(paste0(path,"metadata/paper/benchmark_paper_exp6.csv"), na = character())
#experiment_full <- bind_rows(experiment_full, experiment_second)

# get expression
gex <- read_csv(paste0(path,"metadata/matrix_exp.csv"))
mut_skcm <-read_csv(paste0(path,"metadata/matrix_mut_SKCM.csv"))

# add tgfb scores
emtp_tgf <- emtp
emtp_tgf <- left_join(emtp_tgf, gex[,c("COSMIC ID","TGFB1")], by = "COSMIC ID")

# function for plotting scatter plots
plot_drug <- function(
  df_response = list(ic50 = resp_ic50, auc = resp_auc),
  name_drug,
  emt_score = "mak",
  cancer_type,
  name = NA,
  anno_cells = FALSE,
  orderedcelllines = c("SK-MEL-5","IGR-37","RPMI-7951","A375") # put here what cells to highlight (A-375,SK-MEL1)
  # EMTscores = EMTscores
  # gex = gex
  )
{
  if(is.na(name)){
    name = name_drug
  }
  
  plist <- list()
  resp <- df_response[["auc"]]
  dr <- name_drug
  exp <- gex %>% 
    dplyr::select(c("COSMIC ID"))
  exp <- left_join(EMTscores %>% dplyr::filter(`TCGA Desc` == cancer_type), exp)
  exp <- left_join(exp, resp)
  
  data <- exp
  cortest <- cor.test(data$EMT_score, unlist(data[,dr]))
  p <- ggplot(data, aes(x=EMT_score, y = !!sym(dr))) + 
    geom_smooth(method = "lm", color = "gray50", fill = "gray65") + geom_point() +
    xlab("EMT score") + ylab(paste0("AUC ",name)) + ggtitle(paste0(name," response"))+ #, subtitle = "functional NQO1 expression") +
    theme_minimal() + #+ theme(plot.title = element_text(size = 20),
    #        plot.subtitle = element_text(size = 18, face = "italic"),
    #        axis.title = element_text(size = 20),
    #        axis.text = element_text(size = 15),
    #        strip.text = element_text(size = 18),
    #        legend.position = "none") 
    annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 3)) , 
             x = min(na.omit(data$EMT_score)), y = 0.05, vjust = 0, hjust = 0)
  
  # add labels
  if(anno_cells){
        anno <- read_csv(paste0(path,"data/Model.csv")) %>%
      dplyr::rename(`COSMIC ID` = COSMICID)
    anno$CellLineName[anno$CellLineName == "A-375"] <- "A375"
    data <- left_join(data, anno, by = "COSMIC ID", na_matches = "never")
    data$CellLineName[!(data$CellLineName %in% orderedcelllines)] <- ""
    p <- p +
      geom_text_repel(data = data, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1)
  }
  plist[["auc"]] <- p
  
  resp <- df_response[["ic50"]]
  dr <- name_drug
  exp <- gex %>% 
    dplyr::select(c("COSMIC ID"))
  exp <- left_join(EMTscores %>% dplyr::filter(`TCGA Desc` == cancer_type), exp)
  exp <- left_join(exp, resp)
  
  data <- exp
  cortest <- cor.test(data$EMT_score, unlist(data[,dr])) #Tanespimycin.1026.GDSC1
  p <- ggplot(data, aes(x=EMT_score, y = exp(!!sym(dr)))) + 
    geom_smooth(method = "lm", color = "gray50", fill = "gray65") + geom_point() +
    xlab("EMT score") + ylab(paste0("IC50 ",name," [µM]")) + ggtitle(paste0(name," response"))+ #, subtitle = "functional NQO1 expression") +
    theme_minimal() + #+ theme(plot.title = element_text(size = 20),
    #        plot.subtitle = element_text(size = 18, face = "italic"),
    #        axis.title = element_text(size = 20),
    #        axis.text = element_text(size = 15),
    #        strip.text = element_text(size = 18),
    #        legend.position = "none") 
    annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 3)) , 
             x = min(na.omit(data$EMT_score))+0.3, y = min(na.omit(exp(unlist(data[,dr]))))*0.1, vjust = 0, hjust = 0)+
    scale_y_log10(
      breaks = scales::trans_breaks("log10", function(x) 10^x),
      labels = scales::trans_format("log10", scales::math_format(10^.x)),
      limits = c(min(na.omit(exp(unlist(data[,dr]))))*0.1,max(na.omit(exp(unlist(data[,dr])))*1.1))
    )+
    annotation_logticks(sides = "l")
  
  # add labels
  if(anno_cells){
        anno <- read_csv(paste0(path,"data/Model.csv")) %>%
      dplyr::rename(`COSMIC ID` = COSMICID)
    anno$CellLineName[anno$CellLineName == "A-375"] <- "A375"
    data <- left_join(data, anno, by = "COSMIC ID", na_matches = "never")
    data$CellLineName[!(data$CellLineName %in% orderedcelllines)] <- ""
    p <- p +
      geom_text_repel(data = data, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1)
  }
  
  plist[["ic50"]] <- p
  
  return(plist)
}
```

```{r numbers}
# samples in GDSC drug screen
length(table(resp_ic50$`TCGA Desc`[(!is.na(resp_ic50$`TCGA Desc`)&(resp_ic50$`TCGA Desc` != "UNCLASSIFIED"))])) #31
length(which(!is.na(resp_ic50$`TCGA Desc`)&(resp_ic50$`TCGA Desc` != "UNCLASSIFIED"))) #790

# number of genes in mutations and number of copy number segments
mutations <- list.files(paste0(path,"metadata"), pattern = "matrix_mut", full.names = TRUE)
mutations <- mutations[mutations != "/Users/alexander.ohnmacht/research/marisa/emtpb/metadata/matrix_mut_PANCAN.csv"]

genelist <- c(); cnalist <- c(); nrowsSum <- 0; for(f in mutations){
  tmp <- read_csv(f)
  nrows <- nrow(tmp)
  somaticmut <- unlist(lapply(colnames(tmp), function(x) strsplit(x,"_")[[1]][2]))
  gene <- unlist(lapply(colnames(tmp), function(x) strsplit(x,"_")[[1]][1]))
  cna <- unlist(lapply(gene, function(x) grepl("cna",x,fixed = TRUE)))
  cna <- gene[cna]
  gene <- gene[somaticmut == "mut" & (!is.na(somaticmut))]
  genelist <- c(genelist, gene)
  cnalist <- c(cnalist, cna)
  nrowsSum <- nrows + nrowsSum
}
length(unique(genelist)) #218
length(unique(cnalist)) #802
nrowsSum # 775
```

```{r ablation_correlation_auc, fig.width=3, fig.height=3}
#path <- "/Volumes/pheb/lustre/groups/cbm01/code/alexander.ohnmacht/emtpb/"

#luminespib
ct <- "SKCM"
dr <- "1559-GDSC2"
dr_index <- as.character(which(colnames(resp_auc) == dr)-3)

# get predictions
exp_here <- experiment %>% mutate(idx = 1:nrow(experiment)) %>% filter(score=="" & model_type=="eln" & response_type=="_auc" & (cancer_type == (which(cancertypes == "SKCM")-1)))
ground <- resp_auc %>% filter(`TCGA Desc`=="SKCM") %>% dplyr::select(c("COSMIC ID",dr))
load_path <- paste0(path, 
                    "metadata/run",
                    as.character(exp_here$run),
                    "/predictions/",
                    ct,
                    "/")
load_path <- list.files(path = load_path, pattern = paste0("._",as.character(dr_index),"_."), full.names = TRUE)
# import predictions and fix cell line identities
model_false <- read_csv(load_path[1])
model_false <- left_join(model_false %>% mutate(truth = round(truth, digits = 7)), ground %>% mutate(truth = round(!!sym(dr),digits = 7)), by = "truth")
model_false <- model_false %>% group_by(`COSMIC ID.y`) %>% summarize(preds = mean(preds), truth = mean(truth)) %>% mutate(model = F)
model_true <- read_csv(load_path[2])
model_true <- left_join(model_true %>% mutate(truth = round(truth, digits = 7)), ground %>% mutate(truth = round(!!sym(dr),digits = 7)), by = "truth")
model_true <- model_true %>% group_by(`COSMIC ID.y`) %>% summarize(preds = mean(preds), truth = mean(truth)) %>% mutate(model = T)

preds <- full_join(model_true, model_false, by = "COSMIC ID.y") %>%dplyr::rename(`COSMIC ID` = `COSMIC ID.y`)
q <- full_join(emtp %>% filter(`TCGA Desc` == ct), resp_auc %>% filter(`TCGA Desc` == ct), by="COSMIC ID")
q <- left_join(preds, q, by = "COSMIC ID")
ggplot(q) + 
  stat_smooth(aes(x = truth.x, y = preds.x), color = "grey78", fill = NA,
              method = "lm") + 
  geom_point(aes(x = truth.x, y = preds.x), color = "grey78") +
  stat_smooth(aes(x = truth.x, y = preds.y), color = "grey28", fill = NA,
              method = "lm") +
  geom_point(aes(x = truth.x, y = preds.y), color = "grey28") + 
  theme_minimal() + 
  xlab("observed AUC") + ylab("predicted AUC") + ggtitle("Luminespib") +
  #theme(plot.title = element_text(size = 36),
  #      axis.title = element_text(size = 34),
  #      axis.text = element_text(size = 15)) +
  annotate(geom = "text", x = 0.5, y = 0.87, color = "gray50",hjust = 0,
           label = paste("r =", round(cor.test(q$truth.x, q$preds.x)$estimate, digits = 2))) +
  annotate(geom = "text", x = 0.5, y = 0.9, color = "grey28", hjust = 0,
           label = paste("r =", round(cor.test(q$truth.x, q$preds.y)$estimate, digits = 2)))
```

```{r ablation_correlation_ic50, fig.width=3, fig.height=3}
#luminespib
ct <- "SKCM"
dr <- "1559-GDSC2"
dr_index <- as.character(which(colnames(resp_ic50) == dr)-3)

# get predictions
exp_here <- experiment %>% mutate(idx = 1:nrow(experiment)) %>% filter(score=="" & model_type=="eln" & response_type=="" & (cancer_type == (which(cancertypes == "SKCM")-1)))
ground <- resp_ic50 %>% filter(`TCGA Desc`=="SKCM") %>% dplyr::select(c("COSMIC ID",dr))
load_path <- paste0(path, 
                    "metadata/run",
                    as.character(exp_here$run),
                    "/predictions/",
                    ct,
                    "/")
load_path <- list.files(path = load_path, pattern = paste0("._",as.character(dr_index),"_."), full.names = TRUE)
# import predictions and fix cell line identities
model_false <- read_csv(load_path[1])
model_false <- left_join(model_false %>% mutate(truth = round(truth, digits = 7)), ground %>% mutate(truth = round(!!sym(dr),digits = 7)), by = "truth")
model_false <- model_false %>% group_by(`COSMIC ID.y`) %>% dplyr::summarize(preds = mean(preds), truth = mean(truth)) %>% mutate(model = F)
model_true <- read_csv(load_path[2])
model_true <- left_join(model_true %>% mutate(truth = round(truth, digits = 7)), ground %>% mutate(truth = round(!!sym(dr),digits = 7)), by = "truth")
model_true <- model_true %>% group_by(`COSMIC ID.y`) %>% dplyr::summarize(preds = mean(preds), truth = mean(truth)) %>% mutate(model = T)

preds <- full_join(model_true, model_false, by = "COSMIC ID.y") %>%dplyr::rename(`COSMIC ID` = `COSMIC ID.y`)
q <- full_join(emtp %>% filter(`TCGA Desc` == ct), resp_ic50 %>% filter(`TCGA Desc` == ct), by="COSMIC ID")
q <- left_join(preds, q, by = "COSMIC ID")

ggplot(q) + 
  stat_smooth(aes(x = exp(truth.x), y = exp(preds.x)), color = "grey78", fill = NA,
              method = "lm") + 
  geom_point(aes(x = exp(truth.x), y = exp(preds.x)), color = "grey78") +
  stat_smooth(aes(x = exp(truth.y), y = exp(preds.y)), color = "grey28", fill = NA,
              method = "lm") +
  geom_point(aes(x = exp(truth.y), y = exp(preds.y)), color = "grey28") + 
  theme_minimal() + 
  xlab("observed IC50 [µM]") + ylab("predicted IC50 [µM]") + ggtitle("Luminespib") +
  #theme(plot.title = element_text(size = 36),
  #      axis.title = element_text(size = 34),
  #      axis.text = element_text(size = 15)) +
  annotate(geom = "text", x = 3, y = 1.0, color = "gray50",hjust = 0,
           label = paste("r =", round(cor.test(q$truth.x, q$preds.x)$estimate, digits = 2))) +
  annotate(geom = "text", x = 3, y = 1.4, color = "grey28", hjust = 0,
           label = paste("r =", round(cor.test(q$truth.x, q$preds.y)$estimate, digits = 2)))+
  scale_x_log10(
   breaks = scales::breaks_log(n = 5),
   labels = scales::trans_format("log10", scales::math_format(10^.x))
 ) +
 scale_y_log10(
   breaks = scales::breaks_log(n = 4),
   labels = scales::trans_format("log10", scales::math_format(10^.x))
 )+
  annotation_logticks()
```

```{r volcano_skcm_auc_mak, fig.width=6, fig.height=2}
# Figure 1 volcano for cancer types and drugs (SKCM)
min_hits <- 1
pastel_colors <- brewer.pal(6, "Pastel2")
df_3 <- df %>%
  dplyr::filter(resp_type == "auc") %>%
  dplyr::filter(!is.na(fdr)) %>%
  dplyr::filter(score == "mak") %>%
  dplyr::filter(method %in% c("grfo","eln")) %>%
  dplyr::filter(TCGA == "SKCM")
df_3 <- df_3 %>% dplyr::mutate(score = dplyr::recode(score,"tan"="TAN","mak"="MAK","gsva"="GSVA","secrier"="TW"))
df_3 <- df_3 %>%
  dplyr::select(c(method, drugname, drug,TCGA,score,pvalue,fdr,resp_type,cor_emt,effectsize_mean,delta, lower, upper)) %>%
  tidyr::pivot_wider(names_from = method, values_from = c(pvalue,fdr,cor_emt,effectsize_mean, lower, upper)) %>%
  #dplyr::filter(drug == "1559-GDSC2") %>%
  mutate(id = paste0(drugname," (",TCGA,", ",resp_type,", ",score,")")) %>%
  mutate(strat = paste0(drug,"-",score,"-",resp_type,"-",TCGA)) %>% 
  mutate(filt = paste0(drugname,"-",TCGA))
df_3 <- df_3 %>% group_by(c(strat)) %>% summarize(effectsize_grf = na.omit(effectsize_mean_grfo), 
                                               TCGA = TCGA, 
                                               score = score, 
                                               drugname = drugname,
                                               resp_type = resp_type,
                                               pvalue_eln = na.omit(pvalue_eln),
                                               pvalue_grf = na.omit(pvalue_grfo),
                                               delta = na.omit(delta),
                                               fdr_eln = na.omit(fdr_eln),
                                               filt = filt,
                                               id = id,
                                               lower = na.omit(lower_grfo),
                                               upper = na.omit(upper_grfo)) %>% 
  distinct %>% 
  ungroup()
#df_3$effectsize_grf[df_3$score == "mak"] <- -df_3$effectsize_grf[df_3$score == "mak"] ### FIX THIS !
fdr_threshold <- 0.2
x <- "delta"
y <- "fdr_eln"#"pvalue_eln"
h0 <- max((df_3[,unique(c(y,"fdr_eln"))] %>% arrange(fdr_eln) %>% filter(fdr_eln < fdr_threshold))[,y])
label_data <- df_3[(df_3$fdr_eln < fdr_threshold)&(df_3$filt %in% names(which(table(df_3[df_3$fdr_eln < 0.2,"filt"] ) >=min_hits))),]
#h0 <- sort(unlist(na.omit(df_3[,"pvalue_eln"])))[max(which(sort(unlist(na.omit(df_3[,"fdr_eln"])))<=fdr_threshold))]
p <- ggplot()+
  geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.4, color = pastel_colors[1])+
  geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 1, color = pastel_colors[1])+
  geom_hline(yintercept=-log10(h0), linetype='dotted', color = "grey66", size = 0.9)+
  geom_text_repel(data = label_data,
                  aes(x = !!sym(x), y = -log10(!!sym(y)), label = id), color = "black", show_guide = F, min.segment.length = 0.02,
                  hjust = 1, direction = "y", nudge_x = 0.18- as.numeric(unlist(label_data[,x])), segment.size = 0.1, size = 3
  )+
  theme_minimal()+
  xlab("delta Pearson correlation")+
  ylab("unadjusted -log10(p)")+
  annotate("text", x = min(df_3[,x]%>%na.omit), y = -log10(h0), label = paste0("FDR<",as.character(round(fdr_threshold*100)),"%"), hjust = 0, vjust = 0)
p
```

```{r causal_effect_skcm_auc_full, fig.width=6, fig.height=4}
x <- "c(strat)"
y <- "effectsize_grf"
df_4 <- (df_3[df_3$resp_type == "auc",])
df_4$sig <- (df_4$`c(strat)` %in% label_data$`c(strat)`)
df_4$label <- df_4$id
df_4$label[df_4$sig == FALSE] <- NA

p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper, color = sig), alpha = 0.5) +
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), color = sig), alpha = 1) +
    geom_point(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    #geom_errorbar(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color = "black", alpha = 1) +
    theme_minimal()+
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_blank()
        )+
    xlab("")+
    geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = label),  nudge_y = 0.15, direction = "x", angle = 90)+
    ylab("Estimated causal effect")+
    scale_color_manual(values = c("grey80","black"))
p
```

```{r causal_effect_skcm_auc, fig.width=3, fig.height=2.5}
x <- "id"
# only significants
df_4 <- df_4[df_4$sig,]
p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color="black", alpha = 1) +
    #geom_line(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), group = 1), color = "grey")+ 
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    #geom_ribbon(aes(x = 1:length(!!sym(x)), ymin = lower, ymax=upper), fill = "lightgrey", alpha = 0.4)+
    #geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.2, color = pastel_colors[1])+
    #geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.8, color = pastel_colors[1])+
    #geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = id), color = "black", size = 3)+
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))+
    xlab("")+
    ylab("Estimated causal effect")
p
```

```{r other, fig.width=1.5, fig.height=3}
df_5 <- df_3
df_5 <- df_5[(df_5$`c(strat)` %in% label_data$`c(strat)`),]
resp_help = suppressMessages(read_csv(paste0(path,"metadata/matrix_resp","",".csv"))) # %>% dplyr::select(-c("COSMIC ID","TCGA Desc")))
resp_help_auc = suppressMessages(read_csv(paste0(path,"metadata/matrix_resp","_auc",".csv"))) # %>% dplyr::select(-c("COSMIC ID","TCGA Desc")))
for(i in 1:nrow(df_5)){
    d <- paste0(strsplit(df_5$`c(strat)`[i],"-")[[1]][1:2], collapse = "-")
    if(df_5$resp_type[i] == "ic50"){
        test <- resp_help[resp_help$`TCGA Desc` == df_5$TCGA[i],,drop= F]
        #tt <- exp(c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])*sd(unlist(test[,d])  %>% na.omit)+mean(unlist(test[,d]) %>% na.omit)) -> transform back EMT
        tt <- exp(abs(c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])))
    }
    if(df_5$resp_type[i] == "auc"){
        test <- resp_help_auc[resp_help_auc$`TCGA Desc` == df_5$TCGA[i],,drop= F]
        #tt <- c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])*sd(unlist(test[,d]) %>% na.omit)+mean(unlist(test[,d]) %>% na.omit) -> transform back EMT
        tt <- (abs(c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])))
    }
    df_5$effectsize_grf_e[i] <- tt[1]
    df_5$lower_e[i] <- tt[2]
    df_5$upper_e[i] <- tt[3]
}

# plot confidence band for luminespib AUC
df_6 <- df_5[df_5$id == "Luminespib (SKCM, auc, MAK)",]
error.measurement <- abs(df_6$effectsize_grf-df_6$upper)
ribbondata<- data.frame(x=c(0, 2),
                        ymin=c(  0 - error.measurement,
                                 2*df_6$effectsize_grf - error.measurement),
                        ymax=c( 0  + error.measurement,
                                2*df_6$effectsize_grf + error.measurement)
)
ggplot()+
  geom_point(data = df_6, aes(0, effectsize_grf), shape = 4, size = 3) +  # Scatter plot points
  geom_abline(slope = df_6$effectsize_grf, intercept = df_6$effectsize_grf-df_6$lower,linetype = "dashed") +
  geom_abline(slope = df_6$effectsize_grf, intercept = df_6$effectsize_grf-df_6$upper,linetype = "dashed") +
  geom_ribbon(data=ribbondata, aes(x=x,ymin=ymin,ymax=ymax), inherit.aes = FALSE, alpha = 0.3) +
  geom_abline(intercept = 0, slope = df_6$effectsize_grf, color = "black") +  # Fixed slope line
  theme_minimal()+
  xlim(c(-0.5,2))+
  ylim(c(-0.25,0.05))+
  ylab("delta AUC")+
  xlab("sigma EMT change")+
  scale_x_continuous(breaks=c(0,1,2))
```

```{r volcano_skcm_ic50_mak, fig.width=6, fig.height=2}
# Figure 1 volcano for cancer types and drugs (SKCM)
min_hits <- 1
pastel_colors <- brewer.pal(6, "Pastel2")
df_3 <- df %>%
  dplyr::filter(resp_type == "ic50") %>%
  dplyr::filter(!is.na(fdr)) %>%
  dplyr::filter(score == "mak") %>%
  dplyr::filter(method %in% c("grfo","eln")) %>%
  dplyr::filter(TCGA == "SKCM") 
df_3 <- df_3 %>% dplyr::mutate(score = dplyr::recode(score,"tan"="TAN","mak"="MAK","gsva"="GSVA","secrier"="TW"))
df_3 <- df_3 %>%
  dplyr::select(c(method, drugname, drug,TCGA,score,pvalue,fdr,resp_type,cor_emt,effectsize_mean,delta, lower, upper)) %>%
  tidyr::pivot_wider(names_from = method, values_from = c(pvalue,fdr,cor_emt,effectsize_mean, lower, upper)) %>%
  #dplyr::filter(drug == "1559-GDSC2") %>%
  mutate(id = paste0(drugname," (",TCGA,", ",resp_type,", ",score,")")) %>%
  mutate(strat = paste0(drug,"-",score,"-",resp_type,"-",TCGA)) %>% 
  mutate(filt = paste0(drugname,"-",TCGA))
df_3 <- df_3 %>% group_by(c(strat)) %>% summarize(effectsize_grf = na.omit(effectsize_mean_grfo), 
                                               TCGA = TCGA, 
                                               score = score, 
                                               drugname = drugname,
                                               resp_type = resp_type,
                                               pvalue_eln = na.omit(pvalue_eln),
                                               pvalue_grf = na.omit(pvalue_grfo),
                                               delta = na.omit(delta),
                                               fdr_eln = na.omit(fdr_eln),
                                               filt = filt,
                                               id = id,
                                               lower = na.omit(lower_grfo),
                                               upper = na.omit(upper_grfo)) %>% 
  distinct %>% 
  ungroup()
#df_3$effectsize_grf[df_3$score == "mak"] <- -df_3$effectsize_grf[df_3$score == "mak"] ### FIX THIS !
fdr_threshold <- 0.2
x <- "delta"
y <- "fdr_eln"#"pvalue_eln"
h0 <- max((df_3[,unique(c(y,"fdr_eln"))] %>% arrange(fdr_eln) %>% filter(fdr_eln < fdr_threshold))[,y])
label_data <- df_3[(df_3$fdr_eln < fdr_threshold)&(df_3$filt %in% names(which(table(df_3[df_3$fdr_eln < 0.2,"filt"] ) >=min_hits))),]
#h0 <- sort(unlist(na.omit(df_3[,"pvalue_eln"])))[max(which(sort(unlist(na.omit(df_3[,"fdr_eln"])))<=fdr_threshold))]
p <- ggplot()+
  geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.4, color = pastel_colors[1])+
  geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 1, color = pastel_colors[1])+
  geom_hline(yintercept=-log10(h0), linetype='dotted', color = "grey66", size = 0.9)+
  geom_text_repel(data = label_data,
                  aes(x = !!sym(x), y = -log10(!!sym(y)), label = id), color = "black", show_guide = F, min.segment.length = 0.02,
                  hjust = 1, direction = "y", nudge_x = 0.32- as.numeric(unlist(label_data[,x])), segment.size = 0.1, size = 3
  )+
  theme_minimal()+
  xlab("delta Pearson correlation")+
  ylab("unadjusted -log10(p)")+
  annotate("text", x = min(df_3[,x]%>%na.omit), y = -log10(h0), label = paste0("FDR<",as.character(round(fdr_threshold*100)),"%"), hjust = 0, vjust = 0)
p
```

```{r causal_effect_skcm_ic50_full, fig.width=6, fig.height=4}
x <- "c(strat)"
y <- "effectsize_grf"
df_4 <- (df_3[df_3$resp_type == "ic50",])
df_4$sig <- (df_4$`c(strat)` %in% label_data$`c(strat)`)
df_4$label <- df_4$id
df_4$label[df_4$sig == FALSE] <- NA

p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper, color = sig), alpha = 0.5) +
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), color = sig), alpha = 1) +
    geom_point(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    geom_errorbar(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color = "black", alpha = 1) +
    theme_minimal()+
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_blank()
        )+
    xlab("")+
    geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = label),  nudge_y = 1.5, direction = "x", angle = 90)+
    ylab("Estimated causal effect")+
    scale_color_manual(values = c("grey80","black"))
p
```

```{r causal_effect_skcm_ic50, fig.width=2, fig.height=2.5}
x <- "id"
# only significants
df_4 <- df_4[df_4$sig,]
p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color="black", alpha = 1) +
    #geom_line(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), group = 1), color = "grey")+ 
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    #geom_ribbon(aes(x = 1:length(!!sym(x)), ymin = lower, ymax=upper), fill = "lightgrey", alpha = 0.4)+
    #geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.2, color = pastel_colors[1])+
    #geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.8, color = pastel_colors[1])+
    #geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = id), color = "black", size = 3)+
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))+
    xlab("")+
    ylab("Estimated causal effect")
p
```

```{r emt_correlations_tgfb, fig.width=10, fig.height=2.5}
# Create a grid of scatter plots
my_dens <- function(data, mapping, ...) {
  ggplot(data = data, mapping=mapping) +
    geom_density(..., alpha = 1) 
}

emtpp_tgf <- emtp_tgf
colnames(emtpp_tgf) = c("COSMIC ID","MAK","GSVA","TAN","TW","TCGA Desc","TGFB1")
emtpp_tgf <- emtpp_tgf[emtpp_tgf$`TCGA Desc` == "SKCM",]

# add labels
anno <- read_csv(paste0(path,"data/Model.csv")) %>%
  dplyr::rename(`COSMIC ID` = COSMICID)
anno$CellLineName[anno$CellLineName == "A-375"] <- "A375"
emtpp_tgf <- left_join(emtpp_tgf, anno, by = "COSMIC ID")
orderedcelllines <- c("SK-MEL-5","IGR-37","RPMI-7951","A375") # put here what cells to highlight (A-375,SK-MEL1)
emtpp_tgf$CellLineName[!(emtpp_tgf$CellLineName %in% orderedcelllines)] <- ""

ggp_tgf <- ggpairs(emtpp_tgf, columns = 2:ncol(emtp_tgf), # , aes(colour=`TCGA Desc`
        diag = list(continuous = my_dens)
        ) + scale_fill_manual(values = rev(pastel_colors))+scale_color_manual(values = rev(pastel_colors))+
  theme_minimal()
grid.arrange(ggp_tgf[6,1]+geom_text_repel(data = emtpp_tgf, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1),
             ggp_tgf[6,2]+geom_text_repel(data = emtpp_tgf, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1),
             ggp_tgf[6,3]+geom_text_repel(data = emtpp_tgf, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1),
             ggp_tgf[6,4]+geom_text_repel(data = emtpp_tgf, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1),
             ncol = 4)
```

```{r emt_correlations, fig.width=9, fig.height=11}
emtpp <- emtp
colnames(emtpp) = c("COSMIC ID","MAK","GSVA","TAN","TW","TCGA Desc")
ggp <- ggpairs(emtpp, columns = 2:ncol(emtp), aes(colour=`TCGA Desc`),
        diag = list(continuous = my_dens)
        ) + scale_fill_manual(values = rev(pastel_colors))+scale_color_manual(values = rev(pastel_colors))+
  theme_minimal()
for(i in 1:ggp$nrow) {
  for(j in 1:ggp$ncol){
    if((j == 4)|((j==5)&(i==4)))
      ggp[i,j] <- ggp[i,j] + 
        scale_fill_manual(values=rev(pastel_colors)[-3]) +
        scale_color_manual(values=rev(pastel_colors)[-3])  
    #if((j==5)&(i==5))
    #  ggp[i,j] <- ggp[i,j] + 
    #    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
}
ggp
```

```{r emt_correlations_label, fig.width=3, fig.height=2}
print(ggp[5,5] + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```

```{r emt_correlations_summary, fig.width=12, fig.height=3}
grid.arrange(ggp[5,1]+scale_y_continuous(breaks = c(1,5,9))+ theme(legend.position = "none"),
             ggp[5,2]+scale_y_continuous(breaks = c(1,5,9))+ theme(legend.position = "none"),
             ggp[5,3]+scale_y_continuous(breaks = c(1,5,9))+ theme(legend.position = "none"),
             ggp[5,4]+scale_y_continuous(breaks = c(1,5,9))+ theme(legend.position = "none"),
             ggp[5,4]+scale_y_continuous(breaks = c(1,5,9)),
             ncol = 5
             )
```

```{r mitf, fig.width=3.5, fig.height=3.8}
dat_skcm <- emtp %>% 
  filter(`TCGA Desc` == "SKCM")
dat_skcm <- left_join(dat_skcm, gex[,c("COSMIC ID","MITF")], by = "COSMIC ID")
dat_skcm <- left_join(dat_skcm, mut_skcm, by = "COSMIC ID")
sig_drugs <- unlist(lapply(df_5$`c(strat)`, function(x) paste(strsplit(x,"-")[[1]][1:2],collapse="-"))) # skcm, auc, mak
dat_skcm <- left_join(dat_skcm,resp_ic50[,colnames(resp_ic50) %in% c(sig_drugs,"COSMIC ID")], by = "COSMIC ID")
                      
skcm_emt <- dat_skcm %>%
  mutate(Luminespib = case_when(`1559-GDSC2` < median(na.omit(`1559-GDSC2`)) ~ "high\nresponse", T ~ "low\nresponse")) %>%
  mutate(Staurosporine = case_when(`1034-GDSC2` < median(na.omit(`1034-GDSC2`)) ~ "high\nresponse", T ~ "low\nresponse")) %>%
  mutate(`CHIR-99021` = case_when(`1241-GDSC1` < median(na.omit(`1241-GDSC1`)) ~ "high\nresponse", T ~ "low\nresponse")) %>%
  #mutate(mak = case_when(mak < median(na.omit(mak)) ~ "epithelial", T ~ "mesenchymal")) %>%
  dplyr::select(c("COSMIC ID","mak","gsva","tan","tagliazucchi","MITF","Luminespib","Staurosporine","CHIR-99021")) %>%
  pivot_longer(cols = c("Luminespib","Staurosporine","CHIR-99021")) %>%
  dplyr::rename(drug = name, resp = value) %>%
  #pivot_longer(cols = c("mak","gsva","tan","secrier"))
  dplyr::select(-c("mak","gsva","tan","tagliazucchi")) %>% distinct

stat.test <- skcm_emt %>%
  group_by(drug) %>%
  t_test(MITF ~ resp) %>%
  adjust_pvalue(method = "none") %>%
  add_significance() %>%
  add_y_position()
stat.test$y.position <- stat.test$y.position*1.1 # change position of labels
ggboxplot(skcm_emt, x = "resp", y = "MITF", color = "resp", add = "jitter",facet.by = "drug")+theme_minimal()+
  scale_color_manual(values = c("low\nresponse" = "darkolivegreen4", "high\nresponse" = "darkolivegreen2"))+
  theme(legend.position = "none") + xlab("drug response") + ylab("MITF expression level")+
  stat_pvalue_manual(stat.test, bracket.nudge.y = 0.4, label = "p={p.adj}{p.adj.signif}", size = 2.5)+
  ylim(c(min(na.omit(skcm_emt$MITF)),13.5))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))
```

```{r tf_res}
enr <- readRDS(paste0(path,"metadata/paper/tf_target_enrichments_v2.rds"))
enr_red <- enr %>% filter(sign == "positive") %>% group_by(drug,resp_type,cancertype) %>% slice_min(Adjusted.P.value)

# SKCM: MITF
# BRCA: ESR1
# LUAD: SOX2
```

```{r tf_heatmap, fig.width= 4, fig.height=5}
limma_luminespib <- readRDS(paste0(path,"metadata/paper/tf_diff_genes_luminespib_ic50.rds"))
mitf_target_in_luminespib_hits <- limma_luminespib[limma_luminespib %in% strsplit((enr%>%arrange(Adjusted.P.value))[1,"Genes"][[1]],";")[[1]]]
mitf_target_in_luminespib_hits <- c("MITF",mitf_target_in_luminespib_hits)

# make expression dataframe
rna <- gex %>% dplyr::filter(`COSMIC ID` %in% (EMTscores$`COSMIC ID`[EMTscores$`TCGA Desc` == "SKCM"]))
gex_gdsc_t <- rna[,colnames(rna) %in% c(mitf_target_in_luminespib_hits,"COSMIC ID","TCGA Desc")]
skcm_emt <- EMTscores[EMTscores$`TCGA Desc` == "SKCM",]
skcm_emt <- left_join(skcm_emt, resp_ic50[,c("COSMIC ID","1559-GDSC2"),drop = F])
skcm_emt <- left_join(skcm_emt, mut_skcm[,c("COSMIC ID","BRAF_mut")], by = c("COSMIC ID" = "COSMIC ID"))
tmp <- left_join(skcm_emt, gex_gdsc_t, by = c("COSMIC ID" = "COSMIC ID"))
tmp <- na.omit(tmp)
skcm_hm_df <- tmp

hm_df <- t(skcm_hm_df[,7:(ncol(skcm_hm_df))]) - rowMeans(t(skcm_hm_df[,7:(ncol(skcm_hm_df))]))
#hm_df <- hm_df[names(colors_genes_here),]
#logical <- row.names(hm_df) %in% (names(colors_genes_here)[colors_genes_here != "black"]) # rep(T,nrow(hm_df))
#hm_df <- hm_df[logical,]
#colors_genes_df <- colors_genes_here[logical]

#hm_df <- hm_df[apply(hm_df, 1, var)>=sort(apply(hm_df, 1, var), decreasing = T)[50],] # get 50 best

col_fun = colorRamp2(c(-4, 0, 4), viridis(3))
an <- HeatmapAnnotation(response = skcm_hm_df$`1559-GDSC2`, 
                        BRAF = skcm_hm_df$BRAF_mut,
                        EMT = skcm_hm_df$EMT_score,
                        col = list(response = colorRamp2(range(skcm_hm_df$`1559-GDSC2`), c("grey20", "grey80")),
                                   BRAF = c("1"="grey20","0"="grey80"),
                                   EMT = colorRamp2(range(skcm_hm_df$EMT_score), c("orange","navyblue"))),
                        annotation_legend_param = list(EMT = list(at = c(-1, 4), labels = c("epi.", "mes."))))
set.seed(1234)
draw(Heatmap(hm_df, top_annotation = an, name = "expression", col = col_fun,
             row_names_gp = gpar(fontsize = 6),  #, col = colors_genes_df) # 4
             column_names_gp = gpar(fontsize = 4),
             km = 1, 
             show_column_names = TRUE,
             show_row_dend = F, 
             row_title = NULL), 
     merge_legend = TRUE, heatmap_legend_side = "bottom", 
     annotation_legend_side = "bottom")


# BRAF test
test <- t.test(skcm_hm_df$`1559-GDSC2`~ skcm_hm_df$BRAF_mut)
diff(test$estimate);test
test <- t.test(skcm_hm_df$EMT_score~ skcm_hm_df$BRAF_mut)
diff(test$estimate);test
```

```{r volcano_all, fig.width=9.5, fig.height=5}
# Fig. 2 volcano for all cancer types and drugs (BRCA, SKCM, GBM, LUAD, SCLC, COREAD)
fdr_threshold <- 0.2
df_3 <- df %>%
  #dplyr::filter(resp_type == "ic50") %>%
  dplyr::filter(!is.na(fdr)) %>%
#dplyr::filter(score == "mak") %>%
  dplyr::filter(TCGA != "PANCAN") %>%
  dplyr::filter(method %in% c("grfo","eln")) %>%
  dplyr::filter(TCGA %in% as.character(unlist(unique(na.omit(df[(df$method == "eln")&(df$fdr < fdr_threshold),"TCGA"]))))) 
df_3 <- df_3 %>% dplyr::mutate(score = dplyr::recode(score,"tan"="TAN","mak"="MAK","gsva"="GSVA","secrier"="TW"))
df_3 <- df_3 %>%
  dplyr::select(c(method, drugname, drug,TCGA,score,pvalue,fdr,resp_type,cor_emt,effectsize_mean,delta, lower, upper)) %>%
  tidyr::pivot_wider(names_from = method, values_from = c(pvalue,fdr,cor_emt,effectsize_mean, lower, upper)) %>%
  #dplyr::filter(drug == "1559-GDSC2") %>%
  mutate(id = paste0(drugname," (",TCGA,", ",resp_type,", ",score,")")) %>%
  mutate(strat = paste0(drug,"-",score,"-",resp_type,"-",TCGA)) %>% 
  mutate(filt = paste0(drugname,"-",TCGA))
df_3 <- df_3 %>% group_by(c(strat)) %>% summarize(effectsize_grfo = na.omit(effectsize_mean_grfo), 
                                                  TCGA = TCGA, 
                                                  score = score, 
                                                  drugname = drugname,
                                                  resp_type = resp_type,
                                                  pvalue_eln = na.omit(pvalue_eln),
                                                  pvalue_grf = na.omit(pvalue_grfo),
                                                  delta = na.omit(delta),
                                                  fdr_eln = na.omit(fdr_eln),
                                                  filt = filt,
                                                  id = id,
                                                  lower = na.omit(lower_grfo),
                                                  upper = na.omit(upper_grfo)) %>% 
  distinct %>% 
  ungroup()
#df_3$effectsize_grf[df_3$score == "mak"] <- -df_3$effectsize_grf[df_3$score == "mak"] ### FIX THIS !
x <- "delta"
y <- "fdr_eln"#"pvalue_eln"
howmanyhits <- 3
h0 <- max((df_3[,unique(c(y,"fdr_eln"))] %>% arrange(fdr_eln) %>% filter(fdr_eln < fdr_threshold))[,y])
label_data <- df_3[(df_3$fdr_eln < fdr_threshold)&(df_3$filt %in% names(which(table(df_3[df_3$fdr_eln < fdr_threshold,"filt"] ) >=howmanyhits))),]
#h0 <- sort(unlist(na.omit(df_3[,"pvalue_eln"])))[max(which(sort(unlist(na.omit(df_3[,"fdr_eln"])))<=fdr_threshold))]
p <- ggplot()+
  geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y)), color = TCGA), alpha = 0.2)+
  geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y)), color = TCGA), alpha = 1)+
  geom_hline(yintercept=-log10(h0), linetype='dotted', color = "grey66", size = 0.9)+
  geom_text_repel(data = label_data,
                  aes(x = !!sym(x), y = -log10(!!sym(y)), label = id), color = "black", show_guide = F, min.segment.length = 0.02,
                  hjust = 1, direction = "y", nudge_x = 0.1- as.numeric(unlist(label_data[,x])), segment.size = 0.1, size = 3
                  )+
  theme_minimal()+
  xlab("delta Pearson correlation")+
  ylab("unadjusted -log10(p)")+
  scale_fill_brewer(name = "cancer type",palette="Pastel2", direction=-1) + scale_color_brewer(name = "cancer type",palette="Pastel2", direction=-1)+
  annotate("text", x = min(df_3[,x]%>%na.omit), y = -log10(h0), label = paste0("FDR<",as.character(round(fdr_threshold*100)),"%"), hjust = 0, vjust = 0)
p
```

```{r causal_effect_auc_full, fig.width=9.5, fig.height=5}
x <- "c(strat)"
y <- "effectsize_grfo"
df_4 <- (df_3[df_3$resp_type == "auc",])
df_4$sig <- (df_4$`c(strat)` %in% label_data$`c(strat)`)
df_4$label <- df_4$id
df_4$label[df_4$sig == FALSE] <- NA

df_4$id[1] <- "AZD7762 (BRCA, auc, GSVA, 2)"
df_4$id[8] <- "AZD7762 (BRCA, auc, GSVA, 1)"

p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper, color = sig), alpha = 0.5) +
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), color = sig), alpha = 1) +
    geom_point(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    geom_errorbar(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color = "black", alpha = 1) +
    theme_minimal()+
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_blank()
        )+
    xlab("")+
    geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = label), nudge_y = 0.2, direction = "x", angle = 90)+
    ylab("Estimated causal effect")+
    scale_color_manual(values = c("grey80","black"))
p
```

```{r causal_effect_auc, fig.width=4.0, fig.height=3.5}
x <- "id"
# only significants
df_4 <- df_4[df_4$sig,]
p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color="black", alpha = 1) +
    #geom_line(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), group = 1), color = "grey")+ 
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    #geom_ribbon(aes(x = 1:length(!!sym(x)), ymin = lower, ymax=upper), fill = "lightgrey", alpha = 0.4)+
    #geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.2, color = pastel_colors[1])+
    #geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.8, color = pastel_colors[1])+
    #geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = id), color = "black", size = 3)+
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))+
    xlab("")+
    ylab("Estimated causal effect")
p
```

```{r causal_effect_ic50_full, fig.width=9.5, fig.height=5}
x <- "c(strat)"
y <- "effectsize_grfo"
df_4 <- (df_3[df_3$resp_type == "ic50",])
df_4$sig <- (df_4$`c(strat)` %in% label_data$`c(strat)`)
df_4$label <- df_4$id
df_4$label[df_4$sig == FALSE] <- NA

p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper, color = sig), alpha = 0.5) +
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), color = sig), alpha = 1) +
    geom_point(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    geom_errorbar(data = df_4[df_4$sig,], aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color = "black", alpha = 1) +
    theme_minimal()+
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_blank()
        )+
    xlab("")+
    geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = label), nudge_y = 2, direction = "x", angle = 90)+
    ylab("Estimated causal effect")+
    scale_color_manual(values = c("grey80","black"))
p
```

```{r causal_effect_ic50, fig.width=3.5, fig.height=3.5}
x <- "id"
# only significants
df_4 <- df_4[df_4$sig,]
#df_4$id[1] <- "AZD7762 (BRCA, auc, gsva, 2)"
#df_4$id[8] <- "AZD7762 (BRCA, auc, gsva, 1)"
p <- ggplot(data = df_4)+
    geom_errorbar(aes(x = reorder(!!sym(x), !!sym(y)), ymin = lower, ymax=upper), color="black", alpha = 1) +
    geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)+
    #geom_line(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), group = 1), color = "grey")+ 
    geom_point(aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y)), color = "black", alpha = 1) +
    #geom_ribbon(aes(x = 1:length(!!sym(x)), ymin = lower, ymax=upper), fill = "lightgrey", alpha = 0.4)+
    #geom_point(data = df_3, aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.2, color = pastel_colors[1])+
    #geom_point(data = df_3[(df_3$fdr_eln < fdr_threshold),], aes(x = !!sym(x), y = -log10(!!sym(y))), alpha = 0.8, color = pastel_colors[1])+
    #geom_text_repel(data = df_4, aes(x = reorder(!!sym(x), !!sym(y)), y = !!sym(y), label = id), color = "black", size = 3)+
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))+
    xlab("")+
    ylab("Estimated causal effect")
p
```

```{r luad_rock, fig.width=2.5, fig.height=2.5}
# GSK269962A
df_4 <- df_3
df_4 <- df_4[(df_4$`c(strat)` %in% label_data$`c(strat)`),]

emtpp <- emtp
colnames(emtpp) = c("COSMIC ID","MAK","GSVA","TAN","TW","TCGA Desc")
dat <- emtpp %>% 
  filter(`TCGA Desc` == "LUAD")
sig_drugs <- unlist(lapply(df_4$`c(strat)`[df_4$TCGA == "LUAD"], function(x) paste(strsplit(x,"-")[[1]][1:2],collapse="-"))) # skcm, auc, mak
dat <- left_join(dat,resp_ic50[,colnames(resp_auc) %in% c(sig_drugs,"COSMIC ID")], by = "COSMIC ID")
                      
luad_emt <- dat %>%
  #mutate(mak = case_when(mak < median(na.omit(mak)) ~ "epithelial", T ~ "mesenchymal")) %>%
  mutate(GSK269962A = case_when(`1192-GDSC1` < median(na.omit(`1192-GDSC1`)) ~ "high\nresponse", T ~ "low\nresponse")) %>%
  dplyr::select(c("COSMIC ID","MAK","GSVA","TAN","TW","1192-GDSC1")) %>%
  pivot_longer(cols = c("1192-GDSC1")) %>%
  dplyr::rename(drug = name, resp = value)
  #pivot_longer(cols = c("mak","gsva","tan","tagliazucchi"))
  #dplyr::select(-c("gsva","tan","tagliazucchi")) %>% distinct

data <- luad_emt
cortest <- cor.test(data$MAK, data$resp)
ggplot(data, aes(x=MAK, y = exp(data$resp))) + 
  geom_smooth(method = "lm", color = "gray50", fill = "gray65") + geom_point() +
  xlab("EMT score") + ylab("GSK269962A IC50 [µM]") + ggtitle("GSK269962A response in LUAD") +
  theme_minimal() + #+ theme(plot.title = element_text(size = 20),
                  #        plot.subtitle = element_text(size = 18, face = "italic"),
                  #        axis.title = element_text(size = 20),
                  #        axis.text = element_text(size = 15),
                  #        strip.text = element_text(size = 18),
                  #        legend.position = "none") 
  annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 6)) , 
           x = min(na.omit(data$MAK)), y = min(na.omit(exp(data$resp))*3), vjust = 1, hjust = 0)+
  scale_y_log10(
        breaks = scales::trans_breaks("log10", function(x) 10^x),
        labels = scales::trans_format("log10", scales::math_format(10^.x)),
        limits = c(min(na.omit(exp(data$resp)))*0.8,max(na.omit(exp(data$resp))*1.1))
    )+
  annotation_logticks(sides = "l")
```

```{r brca_subtypes, fig.width=5, fig.height=3}
#, fig.width=4, fig.height=4
#brca subtype50s Jaaks 2023 (only hit for AUC)
brca_subtypes <- read_excel(paste0(path,"metadata/paper/41586_2022_4437_MOESM5_ESM.xlsx"))
mut_brca <-read_csv(paste0(path,"metadata/matrix_mut_BRCA.csv"))

#emtpp <- emtp
#colnames(emtpp) = c("COSMIC ID","MAK","GSVA","TAN","TW","TCGA Desc")
dat <- emtp %>% 
  filter(`TCGA Desc` == "BRCA")
dat <- left_join(dat, gex[,c("COSMIC ID","ESR1")], by = "COSMIC ID")
dat <- left_join(dat, brca_subtypes, by = "COSMIC ID")
dat <- left_join(dat, mut_brca, by = "COSMIC ID")
sig_drugs <- unlist(lapply(df_4$`c(strat)`, function(x) paste(strsplit(x,"-")[[1]][1:2],collapse="-"))) # skcm, auc, mak
dat <- left_join(dat,resp_auc[,colnames(resp_auc) %in% c(sig_drugs,"COSMIC ID")], by = "COSMIC ID")
                      
brca_emt <- dat %>%
  mutate(`AZD7762 (1)` = case_when(`1022-GDSC2` < median(na.omit(`1022-GDSC2`)) ~ "high\nresponse", T ~ "low\nresponse")) %>%
  mutate(`AZD7762 (2)` = case_when(`1402-GDSC1` < median(na.omit(`1402-GDSC1`)) ~ "high\nresponse", T ~ "low\nresponse")) %>%
  #mutate(mak = case_when(mak < median(na.omit(mak)) ~ "epithelial", T ~ "mesenchymal")) %>%
  dplyr::select(c("COSMIC ID","mak","gsva","tan","tagliazucchi","ESR1","AZD7762 (1)","AZD7762 (2)","PAM50","1022-GDSC2","1402-GDSC1","BRCA1_mut","BRCA2_mut")) %>%
  pivot_longer(cols = c("AZD7762 (1)","AZD7762 (2)")) %>%
  dplyr::rename(drug = name, resp = value) %>%
  #pivot_longer(cols = c("mak","gsva","tan","secrier"))
  dplyr::select(-c("gsva","tan","tagliazucchi")) %>% distinct

stat.test <- brca_emt %>%
  group_by(drug) %>%
  t_test(ESR1 ~ resp) %>%
  adjust_pvalue(method = "none") %>%
  add_significance() %>%
  add_y_position()
stat.test$y.position <- stat.test$y.position # change position of labels
ggboxplot(brca_emt, x = "resp", y = "ESR1", color = "resp", add = "jitter",facet.by = "drug")+theme_minimal()+
  scale_color_manual(values = c("low\nresponse" = "darkolivegreen4", "high\nresponse" = "darkolivegreen2"))+
  theme(legend.position = "none") + xlab("drug response") + ylab("ESR1 expression level")+
  stat_pvalue_manual(stat.test, bracket.nudge.y = 0.4, label = "p={p.adj}{p.adj.signif}")+
  ylim(c(min(na.omit(brca_emt$ESR1)),6))

stat.test <- brca_emt %>%
    dplyr::select(-drug) %>%
    distinct %>%
    group_by(PAM50) %>%
    filter(n()>1) %>%
    ungroup() %>%
    mutate(PAM50 = factor(PAM50)) %>%
    t_test(mak ~ PAM50) %>%
    adjust_pvalue(method = "none") %>%
    add_significance() %>%
    add_y_position()
stat.test.anova <- brca_emt %>%
    dplyr::select(-drug) %>%
    distinct %>%
    anova_test(mak ~ PAM50) %>%
    adjust_pvalue(method = "none") %>%
    add_significance() 
ggboxplot(brca_emt%>%dplyr::select(-drug)%>%distinct, x = "PAM50", y = "mak", color = "PAM50", add = "jitter")+theme_minimal()+
  scale_color_manual(values = c("low\nresponse" = "darkolivegreen4", "high\nresponse" = "darkolivegreen2"))+
  theme(legend.position = "none") + xlab("BRCA subtype") + ylab("EMT score")+
  stat_pvalue_manual(stat.test, bracket.nudge.y = 0.4)+
  labs(
    subtitle = get_test_label(stat.test.anova, detailed = TRUE))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))
```

```{r brca_subtypes_2, fig.width=4.5, fig.height=4.5}
stat.test <- brca_emt %>%
    dplyr::select(-drug) %>%
    distinct %>%
    group_by(PAM50) %>%
    filter(n()>1) %>%
    ungroup() %>%
    mutate(PAM50 = factor(PAM50)) %>%
    t_test(`1022-GDSC2` ~ PAM50) %>%
    adjust_pvalue(method = "none") %>%
    add_significance() %>%
    add_y_position()
stat.test.anova <- brca_emt %>%
    dplyr::select(-drug) %>%
    distinct %>%
    #anova_test(mak ~ PAM50) %>%
    anova_test(`1022-GDSC2` ~ PAM50) %>%
    adjust_pvalue(method = "none") %>%
    add_significance() 
brca_emt$`BRCA1/2 mutation` <- factor(sign(brca_emt$BRCA1_mut+brca_emt$BRCA2_mut))
ggboxplot(brca_emt%>%dplyr::select(-drug)%>%distinct, x = "PAM50", y = "1022-GDSC2", color = "mak", shape = "BRCA1/2 mutation", add = "jitter")+
    theme_minimal()+
    #theme(legend.position = "none") +
    xlab("BRCA subtype") + ylab("log(IC50")+
    labs(
        subtitle = get_test_label(stat.test.anova, detailed = TRUE))+
    #stat_pvalue_manual(stat.test, bracket.nudge.y = 0.05)+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), plot.margin = margin(t = 0, r = 0, b = 0, l = 50, unit = "pt"))+
  scale_color_gradient(high = "navyblue", low = "orange", name = "EMT score")
  #   scale_y_log10(
  #       breaks = scales::trans_breaks("log10", function(x) 10^x),
  #       labels = scales::trans_format("log10", scales::math_format(10^.x)),
  #       limits = c(-20,5))+
  #annotation_logticks()

# Reported statistics for brca
summary(lm(data = brca_emt[brca_emt$drug == "AZD7762 (2)",],formula =  `1022-GDSC2` ~ ESR1 + PAM50 + mak))
summary(lm(data = brca_emt[brca_emt$drug == "AZD7762 (2)"&(brca_emt$`BRCA1/2 mutation` == 0),],formula =  `1022-GDSC2` ~ BRCA1_mut + BRCA2_mut + ESR1 + PAM50 + mak))
stat.test.anova <- brca_emt[brca_emt$drug == "AZD7762 (2)",] %>%
    dplyr::select(-drug) %>%
    distinct %>%
    #anova_test(mak ~ PAM50) %>%
    anova_test(`1022-GDSC2` ~ PAM50 + BRCA1_mut + BRCA2_mut + mak) %>%
    adjust_pvalue(method = "none") %>%
    add_significance()


# BRCA wt and basal cancers scatter plot
ggplot((brca_emt%>%dplyr::select(-drug))[(brca_emt$PAM50 == "Basal")&(brca_emt$`BRCA1/2 mutation` == 0),]%>%distinct, aes(x = mak, y = `1022-GDSC2`, shape = `BRCA1/2 mutation`)) +
    geom_point()+
    theme_minimal()+
    theme(legend.position = "none") + xlab("EMT score") + ylab("log(IC50")+
    #stat_pvalue_manual(stat.test, bracket.nudge.y = 0.4)+
    labs(
        subtitle = get_test_label(stat.test.anova, detailed = TRUE))
```

```{r hsp90_17aag_auc, fig.width=2, fig.height=2}
resp <- resp_auc
dr <- "1026-GDSC1"
rs <- read_delim(paste0(path,"metadata/validation/SKCM_rs1800566.txt"), delim = " ") %>%
    mutate(`COSMIC ID` = as.character(CosmicID))
exp <- gex %>% 
  dplyr::select(c("COSMIC ID","NQO1"))
exp <- left_join(EMTscores %>% dplyr::filter(`TCGA Desc` == "SKCM"), exp)
exp <- left_join(exp, resp) %>% 
  mutate(NQO1_binary = ifelse(NQO1 > mean(na.omit(NQO1)),"high","low"))

data <- exp[exp$NQO1_binary == "high",] # & exp$genotype_CT != "-"
cortest <- cor.test(data$EMT_score, unlist(data[,dr]))
p <- ggplot(data, aes(x=EMT_score, y = !!sym(dr))) + 
  geom_smooth(method = "lm", color = "gray50", fill = "gray65") + geom_point() +
  xlab("EMT score") + ylab("AUC Tanespimycin") + ggtitle("Tanespimycin response")+ #, subtitle = "functional NQO1 expression") +
  theme_minimal() + #+ theme(plot.title = element_text(size = 20),
                  #        plot.subtitle = element_text(size = 18, face = "italic"),
                  #        axis.title = element_text(size = 20),
                  #        axis.text = element_text(size = 15),
                  #        strip.text = element_text(size = 18),
                  #        legend.position = "none") 
  annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 3)) , 
           x = min(na.omit(data$EMT_score)), y = 0.05, vjust = 0, hjust = 0)
p
```

```{r hsp90_17aag_auc_anno, fig.width=2, fig.height=2}
anno <- read_csv(paste0(path,"data/Model.csv")) %>%
  dplyr::rename(`COSMIC ID` = COSMICID)
anno$CellLineName[anno$CellLineName == "A-375"] <- "A375"
data <- left_join(data, anno, by = "COSMIC ID", na_matches = "never")
data$CellLineName[!(data$CellLineName %in% orderedcelllines)] <- ""
p_anno <- p +
  geom_text_repel(data = data, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1)
p_anno
```

```{r hsp90_17aag_ic50, fig.width=2, fig.height=2}
resp <- resp_ic50
dr <- "1026-GDSC1"
rs <- read_delim(paste0(path,"metadata/validation/SKCM_rs1800566.txt"), delim = " ") %>%
    mutate(`COSMIC ID` = as.character(CosmicID))
exp <- gex %>% 
  dplyr::select(c("COSMIC ID","NQO1"))
exp <- left_join(EMTscores %>% dplyr::filter(`TCGA Desc` == "SKCM"), exp)
exp <- left_join(exp, resp) %>%
  mutate(NQO1_binary = ifelse(NQO1 > mean(na.omit(NQO1)),"high","low"))

data <- exp[exp$NQO1_binary == "high",] # & exp$genotype_CT != "-"
cortest <- cor.test(data$EMT_score, unlist(data[,dr])) #Tanespimycin.1026.GDSC1
p <- ggplot(data, aes(x=EMT_score, y = exp(!!sym(dr)))) + 
  geom_smooth(method = "lm", color = "gray50", fill = "gray65") + geom_point() +
  xlab("EMT score") + ylab("IC50 Tanespimycin [µM]") + ggtitle("Tanespimycin response")+ #, subtitle = "functional NQO1 expression") +
  theme_minimal() + #+ theme(plot.title = element_text(size = 20),
                  #        plot.subtitle = element_text(size = 18, face = "italic"),
                  #        axis.title = element_text(size = 20),
                  #        axis.text = element_text(size = 15),
                  #        strip.text = element_text(size = 18),
                  #        legend.position = "none") 
  annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 3)) , 
           x = min(na.omit(data$EMT_score))+0.3, y = min(na.omit(exp(unlist(data[,dr]))))*0.1, vjust = 0, hjust = 0)+
  scale_y_log10(
        breaks = scales::trans_breaks("log10", function(x) 10^x),
        labels = scales::trans_format("log10", scales::math_format(10^.x)),
        limits = c(min(na.omit(exp(unlist(data[,dr]))))*0.1,max(na.omit(exp(unlist(data[,dr])))*1.1))
    )+
  annotation_logticks(sides = "l")
p
```

```{r hsp90_17aag_ic50_anno, fig.width=2, fig.height=2}
anno <- read_csv(paste0(path,"data/Model.csv")) %>%
  dplyr::rename(`COSMIC ID` = COSMICID)
anno$CellLineName[anno$CellLineName == "A-375"] <- "A375"
data <- left_join(data, anno, by = "COSMIC ID", na_matches = "never")
data$CellLineName[!(data$CellLineName %in% orderedcelllines)] <- ""
p_anno <- p +
  geom_text_repel(data = data, aes(label = CellLineName), max.overlaps = Inf, min.segment.length = 0, box.padding = 0.5,nudge_x = .15,nudge_y = -.1)
p_anno
```

```{r onalespib_auc, fig.width=2.7, fig.height=2}
EMTscores_ccle <- read_csv(paste0(path,"metadata/EMTscores_ccle.csv"))
drug_response_ccle <- read.delim(paste0(path,"data/depmap/v20.data.curves_post_qc.txt"))
meta_experiment <- read.delim(paste0(path,"data/depmap/v20.meta.per_experiment.txt"))

meta_cell <- read.delim(paste0(path,"data/depmap/v20.meta.per_cell_line.txt"))
meta_drug <- read.delim(paste0(path,"data/depmap/v20.meta.per_compound.txt"))
sample_info <- read.csv(paste0(path,"data/depmap/sample_info.csv"))
sample_info <- left_join(meta_cell[,1:2], sample_info, by = c("ccl_name" = "stripped_cell_line_name"))

# 688229: onalespib
# 50134: tanespimycin
# 362338: SNX-2112
# 347812: CHIR-99012
# 659682: ML320
dr_onalespib <- drug_response_ccle[drug_response_ccle$master_cpd_id %in% c(688229,50134,362338, 347812,659682),]
dr_onalespib <- full_join(dr_onalespib, meta_experiment, by = c("experiment_id"))
dr_onalespib <- left_join(dr_onalespib, meta_drug, by = c("master_cpd_id"))
dr_onalespib <- full_join(dr_onalespib, EMTscores_ccle, by = c("master_ccl_id" = "COSMIC ID")) %>%
  dplyr::filter(`TCGA Desc` == "skin")
dr_onalespib <- left_join(dr_onalespib, sample_info, by = "master_ccl_id")

# filter melanoma
dr_onalespib <- dr_onalespib %>%
  #dplyr::filter(!is.na(COSMICID)) %>%
  #dplyr::filter(Subtype == "Melanoma")
  #dplyr::filter(Sanger_Model_ID != "") %>%
  dplyr::filter(primary_disease == "Skin Cancer")
dr_onalespib$AUC <- unlist(lapply(1:nrow(dr_onalespib), function(i) dr_onalespib$area_under_curve[i]/dr_onalespib$conc_pts_fit[i])) # normalize AUCs with maximum tested concentraiton
dr_onalespib$apparent_ec50_umol[dr_onalespib$apparent_ec50_umol == 0 & !is.na(dr_onalespib$apparent_ec50_umol)] <- 
  min(na.omit(dr_onalespib$apparent_ec50_umol[dr_onalespib$apparent_ec50_umol>0])) # replace 0 ic50 with non-zero minimum ic50 for fixing log-issues
dr_onalespib$apparent_ec50_umol[dr_onalespib$apparent_ec50_umol < 0.0001 & !is.na(dr_onalespib$apparent_ec50_umol)] <- 0.0001 # replace low ic50 with 0.0001 pseudo-ic50 for fixing log-issues
dr_onalespib$apparent_ec50_umol <- unlist(lapply(1:nrow(dr_onalespib), # cap ic50s to maximum tested concentrations
                                                 function(x) ifelse(
                                                   dr_onalespib$apparent_ec50_umol[x] < dr_onalespib$top_test_conc_umol[x],
                                                   dr_onalespib$apparent_ec50_umol[x], 
                                                   dr_onalespib$top_test_conc_umol[x])
                                                 )
                                          )

# check for independent cell lines not included in GDSC
dr_onalespib$`in GDSC` <- as.character((dr_onalespib$COSMICID %in% EMTscores$`COSMIC ID`))
dr_onalespib <- dr_onalespib %>%
  mutate(`in GDSC` = dplyr::recode(`in GDSC`,"TRUE" = "yes", "FALSE" = "no"))

for(drugname in na.omit(unique(dr_onalespib$cpd_name))){
  ccle_skcm_dr <- dr_onalespib[dr_onalespib$cpd_name %in% drugname,]
  ccle_skcm_dr <- (na.omit(ccle_skcm_dr[,c("EMT_score","apparent_ec50_umol","AUC","in GDSC")])) %>% distinct
  cortest <- cor.test(ccle_skcm_dr$EMT_score, (ccle_skcm_dr$AUC))
  cortest
  p <- ggplot(ccle_skcm_dr, aes(x=EMT_score, y=AUC, color = `in GDSC`)) + 
    stat_smooth(method = "lm", color = "gray50", fill = "gray65") + 
    geom_point() + 
    ggtitle(paste0(drugname," in CCLE"))+ theme_minimal()+
    xlab("EMT score") + ylab("AUC") +
    scale_color_manual(values = c("black","grey70"))+
    #theme(plot.title = element_text(size = 20), 
    #                                                                axis.title = element_text(size = 20),
    #                                                                axis.text = element_text(size = 15),
    #                                                                legend.position = "none") 
    annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 3)) , 
             x = min(ccle_skcm_dr$EMT_score[!is.na(ccle_skcm_dr$AUC)]), y = 0.2, vjust = 0, hjust = 0)
  plot(p)
}
```

```{r onalespib_ic50, fig.width=2.7, fig.height=2}
# requires inputs from chunk above

for(drugname in na.omit(unique(dr_onalespib$cpd_name))){
  ccle_skcm_dr <- dr_onalespib[dr_onalespib$cpd_name %in% drugname,]
  ccle_skcm_dr <- (na.omit(ccle_skcm_dr[,c("EMT_score","apparent_ec50_umol","AUC","in GDSC")])) %>% distinct
  cortest <- cor.test(ccle_skcm_dr$EMT_score, (ccle_skcm_dr$apparent_ec50_umol))
  cortest
  p <- ggplot(ccle_skcm_dr, aes(x=EMT_score, y=apparent_ec50_umol, color = `in GDSC`)) + 
    stat_smooth(method = "lm", color = "gray50", fill = "gray65") + 
    geom_point() + 
    ggtitle(paste0(drugname," in CCLE"))+ theme_minimal()+
    scale_color_manual(values = c("black","grey70"))+
    xlab("EMT score") + ylab("IC50 [µM]") +
    #theme(plot.title = element_text(size = 20), 
    #                                                                axis.title = element_text(size = 20),
    #                                                                axis.text = element_text(size = 15),
    #                                                                legend.position = "none") 
    annotate("text", label = paste0("r = ",as.numeric(round(cortest$estimate, 2)),"\n","p = ",round(cortest$p.value, 3)) , 
             x = min(ccle_skcm_dr$EMT_score[!is.na(ccle_skcm_dr$apparent_ec50_umol)])+0.3, y = min(na.omit(ccle_skcm_dr$apparent_ec50_umol))*0.1, vjust = 0, hjust = 0)+
    scale_y_log10(
        breaks = scales::trans_breaks("log10", function(x) 10^x),
        labels = scales::trans_format("log10", scales::math_format(10^.x)),
        limits = c(min(na.omit(ccle_skcm_dr$apparent_ec50_umol))*0.1,max(na.omit(ccle_skcm_dr$apparent_ec50_umol))*1.1)
    )+
  annotation_logticks(sides = "l")
  plot(p)
}
```

```{r luminespib_experiment, fig.width=3, fig.height=3}
anno <- read_csv(paste0(path,"data/Model.csv")) %>%
  rename(`COSMIC ID` = COSMICID)
anno$CellLineName[anno$CellLineName == "A-375"] <- "A375"
data <- full_join(resp_ic50, EMTscores) %>% dplyr::filter(`TCGA Desc` == "SKCM")
data <- left_join(data, anno, by = "COSMIC ID")
#
data$CellLineName[!(data$CellLineName %in% orderedcelllines)] <- ""
ggplot(data, aes(x=EMT_score, y = exp(`1559-GDSC2`), color = EMT_score)) + 
     stat_smooth(method = "lm", color = "gray50", fill = "gray65")+
     geom_point() +
     xlab("EMT score") + ylab("IC50 [µM]") + ggtitle("Luminespib in melanoma (GDSC)") +
     geom_text_repel(data = data %>% dplyr::filter(EMT_score>1.5), aes(label = CellLineName), min.segment.length = 0.1, box.padding = 0, force =1, nudge_x = 5,nudge_y =-0.5, hjust = 0 , color = "black") +
     geom_text_repel(data = data %>% dplyr::filter(EMT_score<1.5), aes(label = CellLineName), min.segment.length = 0.1, box.padding = 0.5, force =1,nudge_x = 0.1 - subset(data, EMT_score<1.5)$EMT_score, hjust =0, direction = "y", color = "black") +
     theme_minimal() + theme(#plot.title = element_text(size = 20), 
         #        axis.title = element_text(size = 20),
         #        axis.text = element_text(size = 15),
         legend.position = "none") +
     scale_color_gradient(high = "navyblue", low = "orange", name = "EMT score")+
     scale_y_log10(
         breaks = scales::trans_breaks("log10", function(x) 10^x),
         labels = scales::trans_format("log10", scales::math_format(10^.x)),
         limits = c(0.005,20)
     )+
  annotation_logticks(sides = "l")
```

```{r prepare_cis_for_validation}
# prepare validation plots
df_3 <- df %>%
  dplyr::filter(!is.na(fdr)) %>%
  dplyr::filter(score == "mak") %>%
  dplyr::filter(method %in% c("grfo","eln")) %>%
  dplyr::filter(TCGA == "SKCM") 
df_3 <- df_3 %>% dplyr::mutate(score = dplyr::recode(score,"tan"="TAN","mak"="MAK","gsva"="GSVA","secrier"="TW"))
df_3 <- df_3 %>%
  dplyr::select(c(method, drugname, drug,TCGA,score,pvalue,fdr,resp_type,cor_emt,effectsize_mean,delta, lower, upper)) %>%
  tidyr::pivot_wider(names_from = method, values_from = c(pvalue,fdr,cor_emt,effectsize_mean, lower, upper)) %>%
  #dplyr::filter(drug == "1559-GDSC2") %>%
  mutate(id = paste0(drugname," (",TCGA,", ",resp_type,", ",score,")")) %>%
  mutate(strat = paste0(drug,"-",score,"-",resp_type,"-",TCGA)) %>% 
  mutate(filt = paste0(drugname,"-",TCGA))
df_3 <- df_3 %>% group_by(c(strat)) %>% summarize(effectsize_grf = na.omit(effectsize_mean_grfo), 
                                                  TCGA = TCGA, 
                                                  score = score, 
                                                  drugname = drugname,
                                                  resp_type = resp_type,
                                                  pvalue_eln = na.omit(pvalue_eln),
                                                  pvalue_grf = na.omit(pvalue_grfo),
                                                  delta = na.omit(delta),
                                                  fdr_eln = na.omit(fdr_eln),
                                                  filt = filt,
                                                  id = id,
                                                  lower = na.omit(lower_grfo),
                                                  upper = na.omit(upper_grfo)) %>% 
  distinct %>% 
  ungroup()


df_4 <- df_3[df_3$drugname == "Luminespib",]
df_5 <- df_4
resp_help = suppressMessages(read_csv(paste0(path,"metadata/matrix_resp","",".csv"))) # %>% dplyr::select(-c("COSMIC ID","TCGA Desc")))
resp_help_auc = suppressMessages(read_csv(paste0(path,"metadata/matrix_resp","_auc",".csv"))) # %>% dplyr::select(-c("COSMIC ID","TCGA Desc")))
for(i in 1:nrow(df_5)){
  d <- paste0(strsplit(df_5$`c(strat)`[i],"-")[[1]][1:2], collapse = "-")
  if(df_5$resp_type[i] == "ic50"){
    test <- resp_help[resp_help$`TCGA Desc` == df_5$TCGA[i],,drop= F]
    #tt <- exp(c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])*sd(unlist(test[,d])  %>% na.omit)+mean(unlist(test[,d]) %>% na.omit)) -> transform back EMT
    tt <- exp(abs(c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])))
  }
  if(df_5$resp_type[i] == "auc"){
    test <- resp_help_auc[resp_help_auc$`TCGA Desc` == df_5$TCGA[i],,drop= F]
    #tt <- c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])*sd(unlist(test[,d]) %>% na.omit)+mean(unlist(test[,d]) %>% na.omit) -> transform back EMT
    tt <- (abs(c(df_5$effectsize_grf[i],df_5$lower[i],df_5$upper[i])))
  }
  df_5$effectsize_grf_e[i] <- tt[1]
  df_5$lower_e[i] <- tt[2]
  df_5$upper_e[i] <- tt[3]
}
```

```{r validation_summary_auc, fig.height=3, fig.width=2.5}
# plot confidence band for luminespib AUC
df_6 <- df_5[df_5$`c(strat)` == "1559-GDSC2-MAK-auc-SKCM",]
error.measurement <- abs(df_6$effectsize_grf-df_6$upper)
#ribbondata<- data.frame(x=c(0, 1),
#                        ymin=c(  0 - error.measurement,
#                                 1*df_6$effectsize_grf - error.measurement),
#                        ymax=c( 0  + error.measurement,
#                                1*df_6$effectsize_grf + error.measurement))
ribbondata<- data.frame(x=c(0, 1),
                        ymin=c(  df_6$effectsize_grf - error.measurement,
                                 1*df_6$effectsize_grf - error.measurement),
                        ymax=c( df_6$effectsize_grf  + error.measurement,
                                1*df_6$effectsize_grf + error.measurement))

# import validation
V <- read_excel(path = paste0(path,validation_aucs))
V$tgf <- factor(unlist(lapply(V$CELL_DRUG, function(x) substr(x,1,1))))
V$emt <- c("mes.","mes.","mes.","mes.","epi.","epi.","epi.","epi.")
V$name <- c("RPMI-7951","A375","RPMI-7951","A375","SK-MEL-5","SK-MEL-5","IGR-37","IGR-37")
#V <- V[!V$name %in% "A375",]
V <- V %>% 
  mutate(label = factor(paste(emt,tgf)))
V_save <- V
  
# summary
s <- ggplot(V, aes(x = name, y = AUC, fill = label, color = label, shape = tgf)) + 
  geom_point(position = position_dodge(width = 0.4), size = 2.5) +
  scale_color_manual(values = c("grey30","darkorange","grey30","navyblue","red")) +
  scale_fill_manual(values = alpha(c("grey30","darkorange","grey30","navyblue","red"), 0.3)) +
  scale_shape_manual(values = c(21, 24)) +
  theme_minimal() + 
  ggtitle("Response to luminespib") +
  guides(fill = guide_legend(override.aes = list(size = 3)))+
  guides(shape = guide_legend(override.aes = list(size = 3)))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
print(s)

Vred <- V %>%
  group_by(name) %>%
  mutate(delta = AUC - lag(AUC, order_by = tgf)) %>%
  na.omit

# paper fig
Vredci <- full_join(Vred %>% 
                  as.data.frame %>%
                  mutate(upper = NA) %>%
                  mutate(lower = NA),
                df_6 %>% 
                  dplyr::select(c("effectsize_grf","lower","upper")) %>% 
                  mutate(label = "n.a.") %>%
                  mutate(name = "null") %>%
                  mutate(emt = "n.a.") %>%
                  mutate(tgf = "n.a.") %>%
                  mutate(upper = ribbondata$ymax[ribbondata$x == 0]) %>%
                  mutate(lower = ribbondata$ymin[ribbondata$x == 0]) %>%
                  mutate(delta = 0)
                ) %>%
  mutate(name = factor(name,levels = c("RPMI-7951","A375","IGR-37","SK-MEL-5","null")))

ggplot(data = Vredci)+
  geom_errorbar(aes(x = name, y = -delta, ymin = lower, ymax=upper), color="black", width = 0.4) +
  geom_point(aes(x = name, y = -delta, color = emt, shape = tgf), size = 2.5) +
  theme_minimal()+
  ylim(c(-0.12,0.05))+
  ylab("delta AUC")+
  xlab("Cell line")+
  scale_color_manual(values = c("mes."="navyblue","epi."="darkorange","null"="black"))+
  scale_shape_manual(values = c(NA, 24)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)
```

```{r validation_summary_ic50, fig.height=3, fig.width=2.5}
# plot confidence band for luminespib AUC
df_6 <- df_5[df_5$`c(strat)` == "1559-GDSC2-MAK-ic50-SKCM",]
error.measurement <- abs(df_6$effectsize_grf-df_6$upper)
# null emt change
#ribbondata<- data.frame(x=c(0, 1),
#                        ymin=c(  0 - error.measurement,
#                                 1*df_6$effectsize_grf - error.measurement),
#                        ymax=c( 0  + error.measurement,
#                                1*df_6$effectsize_grf + error.measurement))
ribbondata<- data.frame(x=c(0, 1),
                        ymin=c(  df_6$effectsize_grf - error.measurement,
                                 1*df_6$effectsize_grf - error.measurement),
                        ymax=c( df_6$effectsize_grf  + error.measurement,
                                1*df_6$effectsize_grf + error.measurement))

# import validation
V <- read_excel(path = paste0(path,validation_ic50s))
V$tgf <- factor(unlist(lapply(V$CELL_DRUG, function(x) substr(x,1,1))))
V$emt <- c("epi.","epi.","mes.","mes.","epi.","epi.","mes.","mes.")
V$name <- c("IGR-37","SK-MEL-5","A375","A375","IGR-37","SK-MEL-5","RPMI-7951","RPMI-7951")
V <- V %>% 
  mutate(label = factor(paste(emt,tgf))) #%>%
  #mutate(IC50 = `IC50(nM)`)
#V <- V[!V$name %in% "A375",]

# summary
s <- ggplot(V, aes(x = name, y = IC50, fill = label, color = label, group = label, shape = tgf)) + 
  geom_point(position = position_dodge(width = 0.4), size = 2.5) +
  scale_color_manual(values = c("grey30","darkorange","grey30","navyblue","red")) +
  scale_fill_manual(values = alpha(c("grey30","darkorange","grey30","navyblue","red"), 0.3)) +
  scale_shape_manual(values = c(21, 24)) +
  theme_minimal() + 
  ggtitle("Response to luminespib") +
  guides(fill = guide_legend(override.aes = list(size = 3)))+
  guides(shape = guide_legend(override.aes = list(size = 3)))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
print(s)

Vred <- V %>%
  group_by(name) %>%
  mutate(IC50 = IC50*0.001) %>% # convert to uM (does not matter since factions below)
  mutate(delta = log(IC50 / lag(IC50, order_by = tgf))) %>% # calc log(c_t/c_u) for comparison
  na.omit

# paper fig
Vredci <- full_join(Vred %>% 
                      as.data.frame %>%
                      mutate(upper = NA) %>%
                      mutate(lower = NA),
                    df_6 %>% 
                      dplyr::select(c("effectsize_grf","lower","upper")) %>% 
                      mutate(label = "n.a.") %>%
                      mutate(name = "null") %>%
                      mutate(emt = "n.a.") %>%
                      mutate(tgf = "n.a.") %>%
                      mutate(upper = ribbondata$ymax[ribbondata$x == 0]) %>%
                      mutate(lower = ribbondata$ymin[ribbondata$x == 0]) %>%
                      mutate(delta = 0)
) %>%
  mutate(name = factor(name,levels = c("RPMI-7951","A375","IGR-37","SK-MEL-5","null")))
ggplot(data = Vredci)+
  geom_errorbar(aes(x = name, y = -delta, ymin = lower, ymax=upper), color="black", width = 0.4) +
  geom_point(aes(x = name, y = -delta, color = emt, shape = tgf), size = 2.5) +
  theme_minimal()+
  #ylim(c(-0.05,0.05))+
  ylab("delta log(IC50)")+
  xlab("Cell line")+
  scale_color_manual(values = c("mes."="navyblue","epi."="darkorange","null"="black"))+
  scale_shape_manual(values = c(NA, 24)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  geom_hline(yintercept=0, linetype='dotted', color = "grey66", size = 0.9)
```

```{r hsp_others, fig.width=2, fig.height=2}
plot_drug(name_drug = "328-GDSC1",
          cancer_type = "SKCM",
          name = "SNX 2112")
plot_drug(name_drug = "1031-GDSC1",
          cancer_type = "SKCM",
          name = "Elesclomol (1)")
plot_drug(name_drug = "1031-GDSC2",
          cancer_type = "SKCM",
          name = "Elesclomol (2)")
#plot_drug(name_drug = "1031-GDSC2",
#          cancer_type = "SKCM",
#          name = "Luminespib (2)")
plot_drug(name_drug = "194-GDSC1",
          cancer_type = "SKCM",
          name = "Luminespib (2)")
plot_drug(name_drug = "154-GDSC1",
          cancer_type = "SKCM",
          name = "CHIR-99021 (2)")
plot_drug(name_drug = "2175-GDSC2",
          cancer_type = "SKCM",
          name = "CHIR-99021 (3)")
plot_drug(name_drug = "1426-GDSC1",
          cancer_type = "SKCM",
          name = "AZD7969")
```

```{r genes_in_mak}
EMTscores_mak <- suppressMessages(read_csv(paste0(path,"metadata/EMT_gs","",".rds")))

```

```{r overall_signatures_luminespib}
# test for differential signature
file_lincs_enrichment <- "metadata/lincs/luminespib_enrichments_all.rds"
t<- readRDS(paste0(path,file_lincs_enrichment))
t$emt <- unlist(lapply(t$id, function(x) strsplit(x," ")[[1]][1]))
t$updn <- unlist(lapply(t$id, function(x) strsplit(x," ")[[1]][2]))
t <- t[unlist(lapply(t$Term, function(x) grepl("GO:",x,fixed = TRUE))),]
t
t_save <- t
t_save$which_signature <- "luminespib"
```

```{r common_signatures_chir_99021_luminespib}
# test for differential signature
file_lincs_enrichment <- "metadata/lincs/chir_990221_luminespib_enrichments_common_dn.rds"
t<- readRDS(paste0(path,file_lincs_enrichment))
t$emt <- unlist(lapply(t$id, function(x) strsplit(x," ")[[1]][1]))
t$updn <- unlist(lapply(t$id, function(x) strsplit(x," ")[[1]][2]))
t <- t[unlist(lapply(t$Term, function(x) grepl("GO:",x,fixed = TRUE))),]
t
t_save2 <- t
t_save2$which_signature <- "luminespib_and_chir990221"
t_save2$id <- "mes down"
t_save2$emt <- "mes"
t_save2$updn <- "down"
t_save <- rbind(t_save, t_save2)
```

# export tables
```{r pathe}
pathe <- paste0(path,"paper/tables/")
```


```{r data_emtscores_gdsc}
emtp_export <- emtp_save[!is.na(emtp_save$`COSMIC ID`),]
write_xlsx(emtp_export, path = paste0(pathe,"data_s1.xlsx"))
```

```{r data_ablation_ci}
df_export <- df %>%
  dplyr::filter(TCGA != "PANCAN") %>%
  dplyr::filter(method != "grf")
write_xlsx(df_export, path = paste0(pathe,"data_s2.xlsx"))
```

```{r data_enrichments_tf}
enrichment_tf_export <- enr_red
write_xlsx(enrichment_tf_export, path = paste0(pathe,"data_s3.xlsx"))
```

```{r data_enrichments_lincs}
t_export <- t_save
write_xlsx(t_export, path = paste0(pathe,"data_s4.xlsx"))
```

```{r data_emtscores_ccle}
emtp_ccle_export <- full_join(meta_experiment, EMTscores_ccle, by = c("master_ccl_id" = "COSMIC ID"))
emtp_ccle_export <- left_join(emtp_ccle_export, sample_info, by = "master_ccl_id") %>%
  dplyr::rename(`COSMIC ID` = COSMICID)
write_xlsx(emtp_ccle_export, path = paste0(pathe,"data_s5.xlsx"))
```

```{r data_validation}
V_export <- full_join(V,V_save)
write_xlsx(V_export, path = paste0(pathe,"data_s6.xlsx"))
```



